### ISSUE TITLE
接口返回状态一直卡死在hl_queue

### ISSUE THREAD

**Issue by pro-cheng** [hexiaochun/hailuo_api_proxy#3]
![Screenshot from 2024-11-17 11-56-48](https://github.com/user-attachments/assets/1b442379-b6da-42ba-b15a-aa853ac66482)
生成视频实际已经失败，但接口返回状态一直卡死hl_queue，导致后续队列任务无法执行。
这两个id  15a52631-389b-408f-b20b-7e9c02f0be59、92b6ebe3-3993-467d-81ec-b5305bedfa88

**Comment by hexiaochun** [comment]
Fix
